markdown: rdiscount
permalink: /:title/
url: https://caicai147.github.io/
#highlighter: pygments
pygments: true
name: caicai
description: caicai
author: caicai
#email: xumenger@126.com
#uyan: xumenger
#weibo: 2679789741
#hub: xumenger 
safe: true
paginate: 70
about: 
